# POST 요청: 회원가입하기
### 
POST http://localhost:4000/auth/signup
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

{
  "isMento": true,
  "mentoType": "coding",
  "nickName": "이헌도2",
  "age": 26,
  "country": "Korea",
  "myInfo": "I love coding and mentoring",
  "subjectTag": "JavaScript",
  "etcTag": "Express",
  "googleId": "112736174799956644168",
  "profileImg": "https://lh3.googleusercontent.com/a/ACg8ocIoxtnabJaMvC_pY92cWg6Z_h-MkVi4jaVdblw-GqFK48AmcJk=s96-c"
}

# GET 요청: 전체 채팅방 조회
###
GET http://localhost:4000/chatrooms
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

# GET 요청: 멘토링중 채팅방 조회
###
GET http://localhost:4000/chatrooms/my-mentorings
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

# POST 요청: 채팅방 조회
###
POST  http://localhost:4000/chatrooms/chat-messages
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

{
	"chatRoomId": 2
}

# POST 요청: 채팅방 읽음 처리
###
POST  http://localhost:4000/chatrooms/read
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

{
  "chatRoomId": 2
}

# GET 요청: 멘토링 찾기
###
GET http://localhost:4000/find-mento

# GET 요청: 프로필 정보 불러오기
###
GET http://localhost:4000/profile
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

# PUT 요청: 프로필 정보 수정
###
PUT http://localhost:4000/profile
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

{
  "nickName": "이헌도",
  "age": 26,
  "mentoType": "문화",
  "subjectTag": "JavaScript",
  "etcTag": "Express",
  "myInfo": "I love coding and mentoring👍"
}

# DELETE 요청: 멘토링 종료
###
DELETE http://localhost:4000/profile/mentoring
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

{
  "mentoringId": 2
}

# POST 요청: 멘토 평가하기
###
POST http://localhost:4000/profile/review
authorization: Bearer ya29.a0AeDClZDeYA0GdRdFpzFvc5FpxHoLkIyfGAhkmkAyVd7DN2q8bRD5aHtyFRLS9WATgfvyGWGBj2qnbsY9iQUsrRYKTZ4nuh51xuqnuq6qTDcOlnfazZ-DdpgAqskVDRJ9CuN4AG31biOBsQymux1p1v0IU1ddrdUthXbyCgfwaCgYKAdISARASFQHGX2MimxayHRYtKHP8NWi0vq1OlA0175
Content-Type: application/json

{
  "mentoId": 1,
  "temperature": 3
}